require('packer').startup(function(use)
  use {
    "wbthomason/packer.nvim",
    "nvim-lualine/lualine.nvim",
    "tpope/vim-commentary",
    "preservim/tagbar",
    "junegunn/fzf.vim",
    "duane9/nvim-rg",
    "nvim-telescope/telescope.nvim",
    "jlcrochet/vim-crystal",
    "voldikss/vim-floaterm",
    "jlcrochet/vim-ruby",
    "tbastos/vim-lua",
    "elixir-editors/vim-elixir",
    "jparise/vim-graphql",
    "slim-template/vim-slim",
    "nvim-lua/plenary.nvim",
    "williamboman/mason.nvim",
    "williamboman/mason-lspconfig.nvim",
    "neovim/nvim-lspconfig",
    "junegunn/fzf", run = function() vim.fn['fzf#install'](0) end,
    "nvim-treesitter/nvim-treesitter", run = function() vim.fn("TSUpdate") end,
    "kyazdani42/nvim-web-devicons",
    "MunifTanjim/nui.nvim",
    "ThePrimeagen/harpoon",
    "mxw/vim-jsx",
    "RRethy/nvim-base16",
    "tamago324/nlsp-settings.nvim",
    "jose-elias-alvarez/null-ls.nvim",
    "jose-elias-alvarez/typescript.nvim",
    "ap/vim-css-color",
  }
end)
