[General]
GeoLocale=system
SensitiveInfoMaskOn=true
autoPlayGif=false
autoScale=true
bForceMaximizeWM=false
captureHDCamera=true
chatListPanelLastWidth=230
conf.crash.enable.auto.uploaddumps=false
conf.webserver=https://zoom.us
currentMeetingId=99533107853
deviceID=74:D8:3E:35:C8:B1
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCloudSwitch=true
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enableWaylandShare=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
host.auto.grab.interval=10
isTransCoding=false
logLevel=info
newMeetingWithVideo=true
playSoundForNewMessage=false
scaleFactor=1
shareBarTopMargin=0
speaker_volume=255
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
timeFormat12HoursEnable=true
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=david.rogers@monterail.com

[AS]
showframewindow=true
