[General]
key_pmi=9023513999
key_pmi_invite_msg="David Rogers is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: David Rogers's Personal Meeting Room\r\n\r\nJoin Zoom Meeting\r\nhttps://zoom.us/j/9023513999?pwd=WVlZRmpQL2toUi9XaklQdmwwVE1HZz09\r\n\r\nMeeting ID: 902 351 3999\r\nPasscode: 3J4hS0\r\n\r\n"
